services:
  hires-scanner:
    build: .
    container_name: hires-scanner
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /volume2/docker/hires-scanner/app:/app
      - /volume2/docker/hires-scanner/data:/data
      - /volume2/docker/hires-scanner/logs:/logs
      - /volume1/Multimedia/Muzyka/Tidal:/music:ro
    working_dir: /app
    command: node server.js
    environment:
      - NODE_ENV=production
      - MUSIC_PATH=/music
      - DATA_PATH=/data
      - LOGS_PATH=/logs
